### ISSUE TITLE
Exceptions raised in worker tasks not propagated to AsyncResult.get() in the app

### ISSUE THREAD

**Issue by rkrell** [earlgreyness/aio-celery#3]
Another issue yet:

There is no clean handling for exceptions happened in async tasks.
The AsyncResult.get() method in the aio_celery app just remains hanging.

Raising exceptions on the app side would help to generate proper response in API endpoints by just catching them and converting to the proper HTTP status.

**Comment by rkrell** [comment]
```
Traceback (most recent call last):
  File "/home/rkrell/.pyenv/versions/project-pypy3.10-7.3.13/lib/pypy3.10/site-packages/aio_celery/worker.py", line 191, in on_message_received
    result = await coro
  File "/home/rkrell/work/project/backend/celery_app/tasks/metadata/tasks.py", line 24, in metadata_task
    raise Exception(desc)
```

**Comment by rkrell** [comment]
I worked around this by copied code parts from the celery project serializing exceptions and test for them on the app side. If an exception is recognized from the result, the serialized dict is converted to Python and raised.

I'd really appreciate native exception support in aio_celery, to avoid AsyncResult.get() from hanging in case an exceptions is raised on the worker.
